language: rust

rust:
  - 1.18.0
  - beta
  - nightly

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  - if [ "$TRAVIS_RUST_VERSION" = "nightly" ]; then
      cargo bench -p gte;
    fi

matrix:
  allow_failures:
    - rust: nightly
    - rust: beta
