[package]
name = "gfxtools"
version = "0.1.0"
authors = ["bow <bow@bow.web.id>"]

[dependencies]
bio = "0.11.0"

[dependencies.clap]
version = "~2.20.5"
default-features = false
features = ["suggestions", "wrap_help"]
