[package]
name = "genomic_fx"
version = "0.1.0"
authors = ["Wibowo Arindrarto <bow@bow.web.id>"]

[dependencies]
bio = "~0.12.0"
csv = "~0.15.0"
itertools = "~0.6.0"
quick-error = "~1.1.0"

[dev-dependencies]
matches = "~0.1.4"
